# global settings
title: "TukangMu"
description: "Cari Tukang Professional Terpercaya"
url: https://aksisoftsby.github.io/tukangmu

plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag

alamat: Jl. Griya Candi Asri Sidoarjo
nohp: 081230097386
email: tukangmupro@gmail.com
facebook: http://facebook.com/
twitter: http://twitter.com
