# global settings
title: "TukangMu"
description: "Cari Tukang Professional Terpercaya"
url: https://aksisoftsby.github.io/tukangmu/

plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
